#!/bin/bash
# Crea usuario normal con la misma ssh key

echo "Nombre del usuario?"
read usuario

# crear usuario
adduser ${usuario}
# concederle privilegios de root
usermod -aG sudo ${usuario}
# compartir la ssh key
rsync --archive --chown=${usuario}:${usuario} ~/.ssh /home/${usuario}
if [ $? -eq 0 ]; 
        then echo "Usuario creado con exito. Ahora intenta entrar como ese usuario.";
    else echo Error. No se pudo; 
fi
exit 0
